

# --Beg Analysis_confDb.py
# --Date inserted: 2012-11-02 09:43:03.767721
##  -*- python -*-  
# db file automatically generated by genconf on: Fri Nov  2 09:42:47 2012## insulates outside world against anything bad that could happen
## also prevents global scope pollution
def _fillCfgDb():
    from GaudiKernel.Proxy.ConfigurableDb import CfgDb

    # get a handle on the repository of Configurables
    cfgDb = CfgDb()

    # populate the repository with informations on Configurables 

    cfgDb.add( configurable = 'TutorialAlgorithm',
               package = 'Analysis',
               module  = 'Analysis.AnalysisConf',
               lib     = 'Analysis' )
    cfgDb.add( configurable = 'DummyAnalysisAlg',
               package = 'Analysis',
               module  = 'Analysis.AnalysisConf',
               lib     = 'Analysis' )
    return #_fillCfgDb
# fill cfgDb at module import...
try:
    _fillCfgDb()
    #house cleaning...
    del _fillCfgDb
except Exception,err:
    print "Py:ConfigurableDb   ERROR Problem with [%s] content!" % __name__
    print "Py:ConfigurableDb   ERROR",err
    print "Py:ConfigurableDb   ERROR   ==> culprit is package [Analysis] !"
# --End Analysis_confDb.py


# --Beg AnalysisTutorial_confDb.py
# --Date inserted: 2012-11-13 14:45:43.705913
##  -*- python -*-  
# db file automatically generated by genconf on: Tue Nov 13 14:45:22 2012## insulates outside world against anything bad that could happen
## also prevents global scope pollution
def _fillCfgDb():
    from GaudiKernel.Proxy.ConfigurableDb import CfgDb

    # get a handle on the repository of Configurables
    cfgDb = CfgDb()

    # populate the repository with informations on Configurables 

    cfgDb.add( configurable = 'TutorialAlgorithm',
               package = 'Analysis',
               module  = 'Analysis.AnalysisTutorialConf',
               lib     = 'AnalysisTutorial' )
    cfgDb.add( configurable = 'DummyAnalysisAlg',
               package = 'Analysis',
               module  = 'Analysis.AnalysisTutorialConf',
               lib     = 'AnalysisTutorial' )
    return #_fillCfgDb
# fill cfgDb at module import...
try:
    _fillCfgDb()
    #house cleaning...
    del _fillCfgDb
except Exception,err:
    print "Py:ConfigurableDb   ERROR Problem with [%s] content!" % __name__
    print "Py:ConfigurableDb   ERROR",err
    print "Py:ConfigurableDb   ERROR   ==> culprit is package [Analysis] !"
# --End AnalysisTutorial_confDb.py


# --Beg Analysis_user_confDb.py
# --Date inserted: 2012-11-22 13:21:34.608924
# db file automatically generated by genconfuser.py on: Thu Nov 22 13:21:22 2012
# No ConfigurableUser specialization in Analysis
# --End Analysis_user_confDb.py
